#!/usr/bin/env bash
set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
TEST_FILE="$ROOT_DIR/molecule/default/tests/test_reporting_for_duty.py"

# -- Colors ----------------------------------------------------------------
GREEN='\033[32m'
RED='\033[31m'
CYAN='\033[36m'
BOLD='\033[1m'
DIM='\033[2m'
RESET='\033[0m'

echo ""
echo -e "  ${CYAN}${BOLD}=============================================="
echo -e "  ARIA — Automated Review & Intelligence Analyst"
echo -e "  Mission 0: Reporting for Duty"
echo -e "  ==============================================${RESET}"

cd "$ROOT_DIR"

# Activate project venv if it exists
if [ -f "$ROOT_DIR/venv/bin/activate" ]; then
    source "$ROOT_DIR/venv/bin/activate"
fi

# Run tests.
# ARIA_COLOR=1 forces color output even when piped through grep.
# conftest.py writes ARIA output to stderr. pytest also leaks assertion
# noise to stderr — filter it out, keep only our indented ARIA lines.
ARIA_COLOR=1 python3 -m pytest "$TEST_FILE" --tb=no --no-header -q 2>&1 1>/dev/null \
    | grep -vE '^(assert |FAILED| *\+  where|  *\+  |[0-9]+ (passed|failed))' || true
EXIT_CODE=${PIPESTATUS[0]}

echo ""
if [ $EXIT_CODE -eq 0 ]; then
    # Mission 0's deliverable lives on the lab node, so write a receipt into
    # the repo — it's the committable artifact 'make submit' opens the PR with.
    mkdir -p "$ROOT_DIR/workspace/reports"
    cat > "$ROOT_DIR/workspace/reports/mission-0-receipt.txt" <<'RECEIPT'
ARIA SUBMISSION RECEIPT
Mission 0: Reporting for Duty
Status: COMPLETE — all phases verified by ARIA (make test)
Rank earned: Midshipman
Duty report filed at /home/cadet/duty-report.txt on sdc-gate

Generated by 'make test' on success. 'make submit' commits this receipt
and opens your review pull request.
RECEIPT
    echo -e "  ${GREEN}${BOLD}=============================================="
    echo -e "  ARIA: All objectives verified."
    echo -e "  Mission 0 status: COMPLETE"
    echo -e ""
    echo -e "  Submission receipt written to"
    echo -e "  workspace/reports/mission-0-receipt.txt"
    echo -e ""
    echo -e "  Duty report received and logged."
    echo -e "  Welcome to the Starfall Defence Corps, Midshipman."
    echo -e "  Your machine is cleared for the Foundation"
    echo -e "  module. Proceed to Mission 1.1: Fleet Census."
    echo -e "  ==============================================${RESET}"
else
    echo -e "  ${RED}${BOLD}=============================================="
    echo -e "  ARIA: Deficiencies detected."
    echo -e "  Review the findings above and correct."
    echo -e "  Run 'make test' again when ready."
    echo -e "  ==============================================${RESET}"
fi

echo ""
exit $EXIT_CODE
